[tool.poetry]
name = "pandas_analysis"
version = "0.1.0"
description = ""
authors = ["Denver Noell <denvernoell@gmail.com>"]

[tool.poetry.dependencies]
# python = ">=3.9,<3.9.7 || >3.9.7,<3.11"
python = ">=3.9,<3.11"
pandas = "^1.4.3"
requests = "^2.28.1"
beautifulsoup4 = "^4.11.1"
plotly = "^5.11.0"
python3-lxml = "^=4.8.0"
# streamlit = "^1.15.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
